package com.yozhikovd.jm_preproject_spring_boot_rest_js_3_1_3.security;

import org.springframework.security.web.context.AbstractSecurityWebApplicationInitializer;

public class SpringSecurityInitializer extends AbstractSecurityWebApplicationInitializer {
}
